//constants for server.js
const majors = ["Africana Studies", "American Studies", "Anthropology", 
    "Architecture", "Art History", "Astronomy", "Astrophysics", "Biochemistry",
    "Biological Sciences", "Chemical Physics", "Chemistry",
    "Cinema and Media Studies", "Classical Civilization", "Classics", 
    "Cognitive and Linguistic Sciences", "Comparative Literary Studies",
    "Computer Science", "Data Science", "East Asian Languages and Cultures",
    "East Asian Studies", "Economics", "Education Studies", 
    "English and Creative Writing", "Environmental Studies",
    "French & Francophone Studies", "French Cultural Studies", "Geosciences",
    "German Studies", "History", "International Relations - Economics", 
    "International Relations - History", 
    "International Relations - Political Science", "Italian Studies", 
    "Jewish Studies", "Latin American Studies", "Mathematics", 
    "Media Arts and Sciences", "Medieval and Renaissance Studies",
    "Middle Eastern Studies", "Music", "Neuroscience", 
    "Peace and Justice Studies", "Philosophy", "Physics", "Political Science",
    "Psychology", "Religion", "Russian", "Russian Area Studies", "Sociology",
    "South Asia Studies", "Spanish and Portuguese", "Studio Art",
    "Theatre Studies", "Women's and Gender Studies", "Individual", "Undeclared"];
const minors = ["Africana Studies", "Anthropology", 
    "Art History", "Asian American Studies", "Astronomy", "Biochemistry",
    "Biological Sciences", "Chemistry", "Chinese Language and Culture",
    "Cinema and Media Studies", "Comparative Race and Ethnicity",
    "Computer Science", "Economics", "Education Studies", 
    "English and Creative Writing", "Environmental Studies", "Geosciences",
    "German Studies", "Global Portuguese Studies", "Health and Society",
    "History", "Italian Studies", "Japanese Language and Culture",
    "Jewish Studies", "Korean Language and Culture", "Latin American Studies",
    "Latina/o Studies", "Mathematics", "Medieval and Renaissance Studies",
    "Middle Eastern Studies", "Music", "Peace and Justice Studies", 
    "Philosophy", "Physics", "Psychology", "Religion", "Russian", "Sociology",
    "South Asia Studies", "Statistics", "Studio Art", 
    "Teaching and Learning Studies", "Women's and Gender Studies"];
const countries = ["Afghanistan", "Albania", "Algeria", "Andorra",
    "Angola", "Antigua and Barbuda", "Argentina", "Armenia", "Australia",
    "Austria", "Azerbaijan", "The Bahamas", "Bahrain", "Bangladesh",
    "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
    "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
    "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia",
    "Cameroon", "Canada", "Central African Republic", "Chad", "Chile",
    "China", "Colombia", "Comoros", "Congo, Democratic Republic of the",
    "Congo, Republic of the", "Costa Rica", "Côte d’Ivoire", "Croatia",
    "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica",
    "Dominican Republic", "East Timor (Timor-Leste)", "Ecuador", "Egypt",
    "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
    "Ethiopia", "Fiji", "Finland", "France", "Gabon", "The Gambia",
    "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala",
    "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary",
    "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel",
    "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
    "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia",
    "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar",
    "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
    "Marshall Islands", "Mauritania", "Mauritius", "Mexico",
    "Micronesia, Federated States of", "Moldova", "Monaco", "Mongolia",
    "Montenegro", "Morocco", "Mozambique", "Myanmar (Burma)",
    "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
    "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway",
    "Oman", "Pakistan", "Palau", "Palestine", "Panama", 
    "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
    "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
    "Saint Kitts and Nevis", "Saint Lucia",
    "Saint Vincent and the Grenadines", "Samoa", "San Marino",
    "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
    "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
    "Solomon Islands", "Somalia", "South Africa", "Spain", "Sri Lanka",
    "Sudan", "Sudan, South", "Suriname", "Sweden", "Switzerland",
    "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Togo",
    "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
    "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", 
    "United Kingdom", "United States", "Uruguay", "Uzbekistan",
    "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", 
    "Zambia", "Zimbabwe"];
const states = ["Alabama", "Alaska", "Arizona", "Arkansas", 
    "California", "Colorado", "Connecticut", "D.C.", "Delaware", 
    "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", 
    "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", 
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", 
    "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire",
    "New Jersey", "New Mexico", "New York", "North Carolina", 
    "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania",
    "Rhode Island", "South Carolina", "South Dakota", "Tennessee",
    "Texas", "Utah", "Vermont", "Virginia", "Washington", 
    "West Virginia", "Wisconsin", "Wyoming"];

module.exports = {
    majors, minors, countries, states
};    